### ISSUE TITLE
Can the data be updated to above the height of 13.5 million blocks? 

### ISSUE THREAD

**Issue by hzysvilla** [tczpl/XBlock-ETH#1]
By the way, can you reveal how the relevant data is collected?
Thx ：)

**Comment by tczpl** [comment]
working on it

数据是通过跑OpenEthereum的节点的三个接口获取完再清洗的，详见[https://www.zhengpeilin.com/research/XBlock-ETH.pdf](https://www.zhengpeilin.com/research/XBlock-ETH.pdf)，不过近期觉得这样还是很麻烦所以打算改一版OE的新接口，不过新服务器的节点还没同步到最新了，焦虑T_T

**Comment by hzysvilla** [comment]
> 

thx

**Comment by martkir** [comment]
@hzysvilla Besides the paper (which is great!) is the code you used to parse the blockchain public?

**Comment by hzysvilla** [comment]
> @hzysvilla Besides the paper (which is great!) is the code you used to parse the blockchain public?

Except the xblock-eth, https://github.com/pandabox-dev/SODA has some modules to parse the data from the go-ethereum. But it didn't suitable for the newest version of the ethereum.

**Comment by tczpl** [comment]
Hi all, the data has been updated to 14,500,000 blocks. Thanks for your attentions very much.
