### ISSUE TITLE
10000000to10999999_BlockTransaction.zip和11000000to11999999_BlockTransaction.zip 压缩包里是老版本normaltranscaction的文件。

### ISSUE THREAD

**Issue by hzysvilla** [tczpl/XBlock-ETH#2]
"10000000to10999999_BlockTransaction.zip":	"https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9vYmRvdGEtbXkuc2hhcmVwb2ludC5jbi86dTovZy9wZXJzb25hbC90Y3pwbF9vYmRvdGFfcGFydG5lcl9vbm1zY2hpbmFfY24vRWY5aWlLOHFaNmRQazNvSzQzM1pJSElCV1JENlJ6NFJpbzhGNmlhd2xUeUFXQT9lPVNvUng5SQ==.zip",
	"11000000to11999999_BlockTransaction.zip":	"https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9vYmRvdGEtbXkuc2hhcmVwb2ludC5jbi86dTovZy9wZXJzb25hbC90Y3pwbF9vYmRvdGFfcGFydG5lcl9vbm1zY2hpbmFfY24vRVRGQkJ0X3BPYkZDbWd6U005eHlYNjRCWkNlUVNBeVplMGdKeTRkQWhxRnVIZz9lPXRza1JPRg==.zip",

**Comment by tczpl** [comment]
我错了，咋上次没上传上去呢。。。近期更新1450w数据的时候将一并更新。。谢谢。。

**Comment by hzysvilla** [comment]
> 我错了，咋上次没上传上去呢。。。近期更新1450w数据的时候将一并更新。。谢谢。。

求老哥整快点，我老板在讨命。 /狗头

**Comment by tczpl** [comment]
兄弟，更新好了。我的。我的

**Comment by liushengzheng** [comment]
这些数据集的属性是什么意思啊，求解答
