### ISSUE TITLE
Where is the CONTRACT CALL dataset mentioned in the paper?

### ISSUE THREAD

**Issue by imtypist** [tczpl/XBlock-ETH#6]
作者你好，请问论文里面提到的合约调用的这个数据集在哪里下载呀，好像不在仓库里面

**Comment by imtypist** [comment]
I found the notes in the website [https://xblock.pro/xblock-eth.html](https://xblock.pro/xblock-eth.html)

> The previous so-called "InternalEtherTransaction", "ContractCall" have been organized as "InternalTransaction", as the same as the Etherscan.io.

I think it solves my question so I close this issue, thanks for authors' efforts!

**Comment by tczpl** [comment]
准确的说ContractCall是会出现在BlockTransaction和InternalTransaction里了~

**Comment by imtypist** [comment]
> 准确的说ContractCall是会出现在BlockTransaction和InternalTransaction里了~

感谢解答！
