### ISSUE TITLE
The CSV file in the TokenInfo folder has an empty address and extra quotes

### ISSUE THREAD

**Issue by yitacls** [tczpl/XBlock-ETH#7]
我发现 TokenInfo 文件夹中的 CSV 文件存在两个问题：

1. 部分行的 'address' 字段为空。

另一些行存在多余的引号，导致多行数据被挤压在同一个字段中。
举例来说，在 ERC20TokenInfo.csv 中，这个问题在以下两个文件中都有体现：
在ERC20TokenInfo.csv中，
![image](https://github.com/tczpl/XBlock-ETH/assets/75364857/afa5feab-5c08-4b08-8b04-b57a1d60ddca)
同样的问题出现在ERC721TokenInfo.csv中，
![image](https://github.com/tczpl/XBlock-ETH/assets/75364857/1405e6a1-ec98-46e0-9325-b84de4c51b83)

2. 此外，在 ERC20TokenInfo.csv 的第 81775 行，存在多余的引号，例如：

```
0x7cc369b5b113e05512700c12db7c3950600f94bf,"All Hearts Be Open" by Susan Bleakley,"Al,1,0
```
，这使得csv文件无法被正确的读取.
![image](https://github.com/tczpl/XBlock-ETH/assets/75364857/029b5da5-f087-4791-8e0c-c8a061bef9e9)
类似的还出现在0x7cc369b5b113e05512700c12db7c3950600f94bf、0xad13bed316ff34c20ea39a452b86900545dd60b9等位置，特别是totalSupply列为空或包含字符串时可能存在此问题

**Comment by tczpl** [comment]
抱歉，这是之前对"\r"和"\""缺少过滤造成的，如果用stat_TokenInfo读取就不会出现，如果用Excel或其他csv工具打开确实就会。已经重新输出了，重新下载即可，应该不会出现这个问题了。
